name: Bitasmbl Evaluation

on:
  push:
    branches: [main]

jobs:
  evaluate:
    runs-on: ubuntu-latest

    steps:
      - name: Install Bitasmbl CLI
        run: npm install -g github:he1snber8/bitasmbl-cli

      - name: Run Bitasmbl
        run: bitasmbl evaluate --project=123

